### ISSUE TITLE
Unable to use in blueprint files

### ISSUE THREAD

**Issue by AggressivelyMeows** [bohea/sanic-limiter#12]
I cannot find a way to use this in blueprint files. Every attempt leads to the same issue:
```py
[2019-06-27 20:12:41 +0000] [32202] [ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sanic/app.py", line 584, in handle_request
    response = await self._run_request_middleware(request)
  File "/usr/local/lib/python3.6/dist-packages/spf/framework.py", line 466, in _run_request_middleware
    response = middleware(request)
  File "/usr/local/lib/python3.6/dist-packages/sanic_limiter/extension.py", line 155, in __check_request_limit
    view_handler = self.app.router.routes_static.get(endpoint, None)
AttributeError: 'NoneType' object has no attribute 'router
```
The limiter is added via `init_app` in `before_server_start`. I want to have a common limiter that i can import insted of having to make a limiter per blueprint file as i have many files

**Comment by bohea** [comment]
I think @J-France fixed this bug #13
