### ISSUE TITLE
there are something wrong when I used

### ISSUE THREAD

**Issue by miss85246** [bohea/sanic-limiter#19]
There are some exception in sanic-limiter:
I have three file like this:
``` text
 ├──server.py
 ├──Limiter.py
 └──Views.py
```
I declare variable in Limiter.py :
```python
from sanic_limiter import Limiter

def get_real_ip(request):
    try:
        headers = request.headers
        ip_list = headers.getone("x-forwarded-for", ",").split(",")
        ip_demo = ip_list[0] or None
        ip = ip_demo or headers.getone("x-real-ip", "")
    except Exception as e:
        raise e
    return ip.strip()

limiter = Limiter(global_limits=['500/day', '100/hour', '20/minute'], key_func=get_real_ip)
```
and init_app in server.py:
```python
from sanic import Sainc
from server import limiter

PROJECT_CONFIG = dict()
LOGGING_CONFIG = dict()

app = Sanic('ln_user', log_config=LOGGING_CONFIG)
app.config.update(PROJECT_CONFIG)
limiter.init_app(app)
```
finally I use limiter in Views.py:
```python
import limiter from Limiter

class AccountLoginView(HTTPMethodView):
    @limiter.limit("100/hour;10/minute")
    def get(request):
        pass
```
when I access this view, some exception were raised:
```shell
Traceback (most recent call last):
  File "/home/centos7/.virtualenvs/dev/lib/python3.8/site-packages/sanic/app.py", line 908, in handle_request
    response = await self._run_request_middleware(
  File "/home/centos7/.virtualenvs/dev/lib/python3.8/site-packages/sanic/app.py", line 1265, in _run_request_middleware
    response = middleware(request)
  File "/home/centos7/.virtualenvs/dev/lib/python3.8/site-packages/sanic_limiter/extension.py", line 155, in __check_request_limit
    view_handler = self.app.router.routes_static.get(endpoint, None)
AttributeError: 'NoneType' object has no attribute 'router'
```
Then I checked your source code, I found there used  attribute `self.app`.
I don't pass `app` to class Limiter, so self.app is None
```python
class Limiter(object):
    def __init__(self, app=None
                 , key_func=None
                 , global_limits=[]
                 , strategy=None
                 , storage_uri=None
                 , storage_options={}
                 , swallow_errors=False
                 ):
        self.app = app        # here pass the `app` to self.app 
        self.logger = logging.getLogger("sanic-limiter")
        ...
```
in your `init_app` function, I pass the `app` to function but you don't assignment parameter `app` to `self.app`
I think there is something wrong, your need assignment it and after that, the problem will be solved
I'm not sure I'm right and this is just my personal opinion.
If I'm wrong, please tell me why, thanks
```python
    def init_app(self, app):
        """
        :param app: :class:`sanic.Sanic` instance to rate limit.
        """
       # self.app = app    You need to add an assignment statement here
        self.enabled = app.config.setdefault(C.ENABLED, True)
        self._swallow_errors = app.config.setdefault(
            C.SWALLOW_ERRORS, self._swallow_errors
        )
        self._storage_options.update(
            app.config.get(C.STORAGE_OPTIONS, {})
        )
        self._storage = storage_from_string(
            self._storage_uri
            or app.config.setdefault(C.STORAGE_URL, 'memory://'),
            **self._storage_options
        )
        strategy = (
            self._strategy
            or app.config.setdefault(C.STRATEGY, 'fixed-window')
        )
        if strategy not in STRATEGIES:
            raise ConfigurationError("Invalid rate limiting strategy %s" % strategy)
        self._limiter = STRATEGIES[strategy](self._storage)

        conf_limits = app.config.get(C.GLOBAL_LIMITS, None)
        if not self._global_limits and conf_limits:
            self._global_limits = [
                ExtLimit(
                    limit, self._key_func, None, False, None, None, None
                ) for limit in parse_many(conf_limits)
                ]
        app.request_middleware.append(self.__check_request_limit)
```

**Comment by pythops** [comment]
@miss85246 
Try to install the package from master as it's up to date compared to the pypi version.
```
pip install git+https://github.com/bohea/sanic-limiter.git@master
```
